name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: koikirin/buildplate/.github/workflows/publish_npm.buildplate.yml@v1